### ISSUE TITLE
Request: Hide Dock Icon

### ISSUE THREAD

**Issue by r3volution11** [geraldoramos/crypto-bar#25]
As the title says I'd love to hide the dock icon. It's a menu bar app after all. ❤️

**Comment by geraldoramos** [comment]
The dock icon is hidden by default. The only reason you see it is because you used `CommandOrControl+Shift+Control+Option+D` at some point. When you run that, the dock icon and dev tools will be visible until you restart the app. This shortcut is supposed to be as hidden as possible and only used for troubleshooting.

As mentioned in your other issue, having this global shortcut can interfere if you have the same shortcut set in another app (I will fix that in the next release by either making it even crazier shortcut or replacing it by another method)
